### ISSUE TITLE
Financial Costing & Project Needs

### ISSUE THREAD

**Issue by DynamoRed** [RMR-Inc/loyaltycard_global#1]
- [x] Planification des différentes tâches à réaliser, chiffrage financier de la partie développement

- [x] une première matrice RACI devra être présentée ainsi qu'un premier diagramme Gantt

- [x] Livrable Gestion de projet en Docx:
a. Organisation du projet (expression du besoin, équipe projet, tâches, jalons avec analyse des différentes phases du projet et livrables réunions, proposition d'un plan d'exécution des tâches, analyse de risques liée au projet)
b. Pilotage de projet (Suivi des Ressources, diagramme de Gantt prévisionnel...)
c. Communication projet (Plan de communication, technologies et supports...)

**Comment by DynamoRed** [comment]
## Matrice RACI
<img src="https://user-images.githubusercontent.com/44113746/151718504-3fef6f3f-f075-47d5-a309-187837fd1a69.png" width="500px" />

**Comment by Maubry94** [comment]
##Chiffrage financier de développement
[Chiffrage Financier Developpement.xlsx](https://github.com/RMR-Inc/loyaltycard_global/files/7966954/Chiffrage.Financier.Developpement.xlsx)

**Comment by Maubry94** [comment]
## Chiffrage financier de développement V1
[Chiffrage Financier Developpement.xlsx](https://github.com/RMR-Inc/loyaltycard_global/files/7966956/Chiffrage.Financier.Developpement.xlsx)

**Comment by Maubry94** [comment]
## Reprise de l'ensemble des coûts avec proposition d'une offre commerciale V1
[Reprise de l'ensemble des coûts avec proposition d'une offre commerciale - Mission 3.xlsx](https://github.com/RMR-Inc/loyaltycard_global/files/7966958/Reprise.de.l.ensemble.des.couts.avec.proposition.d.une.offre.commerciale.-.Mission.3.xlsx)

**Comment by Maubry94** [comment]
## Digramme de Gantt V1
![Diagramme de Gantt PA](https://user-images.githubusercontent.com/58041322/151718778-b58bd23c-0ce9-4059-a0da-746fb1474726.png)

[Digramme de Gantt PA.zip](https://github.com/RMR-Inc/loyaltycard_global/files/7966960/Digramme.de.Gantt.PA.zip)

**Comment by Maubry94** [comment]
## Gestion des risques V1
[Gestion des risques V1.pdf](https://github.com/RMR-Inc/loyaltycard_global/files/8016987/Gestion.des.risques.V1.pdf)
