### ISSUE TITLE
cURL testing & firewall and vpn research

### ISSUE THREAD

**Issue by DynamoRed** [RMR-Inc/loyaltycard_global#5]
- [x] Recherches sur les Firewall PFSENSE ou OPNSENSE et les VPN site à site (IPSEC par exemple)

- [x] Programme C de test sur l'utilisation de cURL

**Comment by Dropaa** [comment]
## Programme C Test de cURL
[Code source Test cURL.zip](https://github.com/RMR-Inc/loyaltycard_global/files/7967000/Code.curl.PA.zip)

**Comment by Dropaa** [comment]
OPNSENSE  : Des mise à jours fréquentes,
Basé sur HardenedBSD au lieu de FreeBSD
Pas de faille de sécurité majeure récemment.
OPNSENSE possède un Wireguard VPN
Possède également plus de plugin que PFSENSE (75 plugins)
OPNSENSE est automatique et possède également un système de chiffrement des données de backup via Google Drive ou NexCloud.

Les VPN permettent d’accéder et d’échanger des données confidentielles en toute sécurité sur des infrastructures de réseau partagées. Cela permettra de sécuriser notre infrastructure et sécuriser la circulation de nos données.

**Comment by Dropaa** [comment]
[Firewall IPSEC.pdf](https://github.com/RMR-Inc/loyaltycard_global/files/7979013/Firewall.IPSEC.pdf)
