### ISSUE TITLE
Setup Docs

### ISSUE THREAD

**Issue by DynamoRed** [RMR-Inc/loyaltycard_global#6]
- [x] Descriptif fonctionnel détaillé et numéroté de la partie C

- [x] Descriptif fonctionnel détaillé et numéroté de la partie Application Web

**Comment by Maubry94** [comment]
## Descriptif fonctionnel détaillé et numéroté de la partie Application Web

[Descriptif.Fonctionnel.Application.Web.-.PA.2021-22.ESGI.pdf](https://github.com/RMR-Inc/loyaltycard_global/files/7966982/Descriptif.Fonctionnel.Application.Web.-.PA.2021-22.ESGI.pdf)

**Comment by DynamoRed** [comment]
## Descriptif Fonctionnel Web
[Descriptif Web.pdf](https://github.com/RMR-Inc/loyaltycard_global/files/7966981/Web.pdf)

**Comment by DynamoRed** [comment]
## Descriptif Fonctionnel C
[Descriptif C.pdf](https://github.com/RMR-Inc/loyaltycard_global/files/7966984/C.pdf)
